spring.application.name=member
server.port=0
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/GymProjectMemberDb?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
spring.web.resources.static-locations=file:C:/Users/nethupama/SpringBoot/Gym_Project/Gym_Project/uploads/
spring.mvc.static-path-pattern=/uploads/**
eureka.client.service-url.defaulatZone=http://localhost:8761/eureka
image.base.url=https://firebasestorage.googleapis.com/v0/b/uploadimage-8a752.appspot.com/o/
